### Register : successful
POST {{host}}/user/register
Content-Type: application/json

{
  "name": "123456789",
  "email": "email@example.com",
  "tel": "13045678913",
  "pass": "462ab506377df2508aed2bea7e2662aa",
  "role": "CONSUMER"
}



### Login : successful
POST {{host}}/user/login
Content-Type: application/json

{
  "tel": "13045678913",
  "pass": "462ab506377df2508aed2bea7e2662aa",
  "role": "CONSUMER"
}